apiVersion: v1
kind: Service
metadata:
  name: {{ include "reminder-worker.fullname" . }}
  labels:
    {{- include "reminder-worker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: worker
  selector:
    {{- include "reminder-worker.selectorLabels" . | nindent 4 }}